#!/bin/bash
#############
#Clark brooks
############
# Setting Gateway infrastructure



# Argument 1 will be first part of the network address ($ipAddrees123)
ipAddrees123="$1"

# Argument 4 Domain name  (template)
domainName="$2"




rm -f /etc/sysconfig/network-scripts/ifcfg-ens160

{
	PROXY_METHOD=none
	BROWSER_ONLY=no
	DEFROUTE=yes
	IPV4_FAILURE_FATAL=no
	IPV6 INIT=no
	IPV6
	DEFROUTE=yes
	IPV6_FAILURE_FATAL=no
	NAME=ens160
	QUID=32d7c5eb-362e-4764-8ddd-847ab5c94e8e
	DEVICE=ens160
	ONBOOT=yes
	IPADDR=$ipAddrees123.1
	NETMASK=255.255.255.0
	GATEWAY=192.168.3.17
	BROADCAT=$ipAddrees123.255
	NETWORK=$ipAddrees123.0
	USERCTL=no
	HWADDR=00:50:56:32:F0:4D
	TYPE=Ethernet
	PREFIX=24
	BOOTPROTO=dhcp
}/etc/sysconfig/network-scripts/ifcfg-ens160


rm -f /etc/sysconfig/network-scripts/ifcfg-ens192

{
	DEVICE=ens192
	HWADDR=00:50:56:32:B2:6A
	IPADDR=192.168.3.17
	BROADCAST=192.168.3.255
	NETMASK=255.255.0.0
	NETWORK=192.168.0.0
	GATEWAY=192.168.1.1
	ONBOOT=yes
	TYPE=Ethernet
	USERCTL=no
	IPV6INIT=no
	PROXY_METHOD=none
	BROWSER_ONLY=no
	PREFIX=16
	DEFROUTE=yes
	IPV4_FAILURE_FATAL=no
	IPV6_DEFROUTE=yes
	IPV6_FAILURE_FATAL=no
	NAME="System ens192"
	UUID=83da7580-2101-c722-2438-d0006c28c73
	BOOTPROTO=none
}/etc/sysconfig/network-scripts/ifcfg-ens192

systemctl restart NetworkManager


# do i need this one ?
rm -f /etc/hosts
{
	127.8.8.1 1:1	nat localhost localhost. localdomain localhost4 localhost4. localdomain4
	::1				localhost localhost. localdomain localhost6 localhost.localdomain6

}/etc/hosts



rm -f /etc/sysconfig/network
{
	# Created by anaconda
	NETWORKING=yes
	HOSTNAME=nat
	GATEWAY=192.168.3.17
	
}/etc/sysconfig/network


rm -f /etc/resolv.conf
{
	# Generated by NetworkManager
	search $domainName.com easlab.co.uk
	nameserver $ipAddrees123.3

}/etc/resolv.conf


iptables -F
iptables -t nat -F
iptables -t mangle -F


iptables -X
iptables -t nat -X
iptables -t mangle -X

iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE


iptables -A FORWARD -i eth1 -j ACCEPT
echo 1 > /proc/sys/net/ipv4/ip_forward


rm -f /etc/sysctl.conf
{
	# sysctl settings are defined through files in
	# /usr/lib/sysctl.d/, /run/sysctl.d/, and /etc/sysctl.d/.
	#
	# Vendors settings live in /usr/lib/sysctl.d/.
	# To override a whole file, create a new file with the same in
	# /etc/sysctl.d/ and put new settings there. To override
	# only specific settings, add a file with a lexically later
	# name in /etc/sysctl.d/ and put new settings there.
	#
	# For more information, see sysctl.conf (5) and sysct1.d(5).

	net.ipv4.ip_forward=1

}/etc/sysctl.conf

service iptables save
service iptables restart



systemctl restart NetworkManager






