version: '3.4'

services:
  scorekeeper1:
    image: scorekeeper1
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    
mongodb:
  image: mongodb:latest
  ports:
    - 27017:27017
    