#!/bin/bash
#############
#Clark brooks
############
# Setting Gateway infrastructure

# Argument 1 will be first part of the network address ($ipAddrees123)
ipAddrees123="10.0.0"

# Argument 4 Domain name  (template)
domainName="clark"

yum install iptables-services

rm -f /etc/sysconfig/network-scripts/ifcfg-ens160
rm -f /etc/sysconfig/network-scripts/ifcfg-ens192

systemctl restart NetworkManager

echo "
	PROXY_METHOD=none
	BROWSER_ONLY=no
	DEFROUTE=yes
	IPV4_FAILURE_FATAL=no
	IPV6INIT=no
	DEFROUTE=yes
	IPV6_FAILURE_FATAL=no
	NAME=ens192
	DEVICE=ens192
	ONBOOT=yes
	IPADDR=$ipAddrees123.1
	NETMASK=255.255.255.0
	GATEWAY=192.168.1.1
	BROADCAT=$ipAddrees123.255
	NETWORK=nat
	NETWORKING=yes
	USERCTL=no
	HWADDR=00:50:56:32:F0:4D
	TYPE=Ethernet
	PREFIX=24
	BOOTPROTO=static
" >>/etc/sysconfig/network-scripts/ifcfg-ens192



echo "
	DEVICE=ens160
	HWADDR=00:50:56:32:B2:6A
	BROADCAST=192.168.3.255
	NETMASK=255.255.255.0
	ONBOOT=yes
	TYPE=Ethernet
	USERCTL=no
	IPV6INIT=no
	PROXY_METHOD=none
	BROWSER_ONLY=no
	PREFIX=16
	DEFROUTE=yes
	IPV4_FAILURE_FATAL=no
	IPV6_DEFROUTE=yes
	IPV6_FAILURE_FATAL=no
	NAME=ens160
	UUID=32d7c5eb-362e-4764-8ddd-847ab5c94e8e
	BOOTPROTO=dhcp
" >>/etc/sysconfig/network-scripts/ens160

systemctl restart NetworkManager

rm -f /etc/hosts
echo "
	127.0.0.1 nat localhost.localdomain localhost
" >>/etc/hosts

rm -f /etc/sysconfig/network
echo "
	# Created by anaconda  Test
	NETWORKING=yes
	HOSTNAME=nat
	GATEWAY=192.168.1.1

" >>/etc/sysconfig/network

rm -f /etc/resolv.conf
echo "
	# Generated by NetworkManager
	search $domainName.com easlab.co.uk
	nameserver 8.8.8.8
" >>/etc/resolv.conf

yum -y install iptables-services

iptables -F
iptables -t nat -F
iptables -t mangle -F

iptables -X
iptables -t nat -X
iptables -t mangle -X

iptables -t nat -A POSTROUTING -o ens160 -j MASQUERADE

iptables -A FORWARD -i ens192 -j ACCEPT
echo 1 >/proc/sys/net/ipv4/ip_forward

rm -f /etc/sysctl.conf
echo "
	# sysctl settings are defined through files in
	# /usr/lib/sysctl.d/, /run/sysctl.d/, and /etc/sysctl.d/.
	#
	# Vendors settings live in /usr/lib/sysctl.d/.
	# To override a whole file, create a new file with the same in
	# /etc/sysctl.d/ and put new settings there. To override
	# only specific settings, add a file with a lexically later
	# name in /etc/sysctl.d/ and put new settings there.
	#
	# For more information, see sysctl.conf (5) and sysct1.d(5).

	net.ipv4.ip_forward=1

" >>/etc/sysctl.conf

service iptables save
service iptables restart

systemctl restart NetworkManager
